### PR TITLE
Failed trying to implement gzip.open

### PR DESCRIPTION
**Pull request by timknut**
Check out. https://github.com/haraldgrove/snptranslate/compare/master...timknut:master 

Converting a simple list file now yields..

```
Traceback (most recent call last):
  File "/mnt/users/tikn/for_folk/geno/geno_imputation/scripts/snptranslate/ioSNP.py", line 168, in <module>
    main()
  File "/mnt/users/tikn/for_folk/geno/geno_imputation/scripts/snptranslate/ioSNP.py", line 161, in main
    genos = gen1.readFile(args.input,rmark)
  File "/mnt/users/tikn/for_folk/geno/geno_imputation/scripts/snptranslate/iomods/ioGenomelist.py", line 87, in readFile
    ped,mark = self.updatePedMark(input)
TypeError: updatePedMark() takes exactly 3 arguments (2 given)
```

Pointers?

### CODE REVIEW

**Comment by haraldgrove** [comment]
Why is isgzip added as an input parameter to the updatePedMark function? I think you could remove that and it would work fine.

**Comment by timknut** [comment]
No, it complained. I was just randomly trying things. Will try more, but might give up. ;)

**Comment by timknut** [comment]
@haraldgrove It does not find the isgzip function:
```bash
tikn@login-0:~/for_folk/geno/geno_imputation/scripts/snptranslate/example_data$ ./run_example.sh
Converting FinalReport_toy.txt
Traceback (most recent call last):
  File "../ioSNP.py", line 168, in <module>
    main()
  File "../ioSNP.py", line 161, in main
    genos = gen1.readFile(args.input,rmark)
  File "/mnt/users/tikn/for_folk/geno/geno_imputation/scripts/snptranslate/iomods/ioGenomelist.py", line 87, in readFile
    ped,mark = self.updatePedMark(input)
  File "/mnt/users/tikn/for_folk/geno/geno_imputation/scripts/snptranslate/iomods/ioGenomelist.py", line 39, in updatePedMark
    if isgzip(input):
NameError: global name 'isgzip' is not defined
```
Any idea?

**Comment by timknut** [comment]
It is now fixed @haraldgrove .
Needed to `self.isgzip`

**Comment by haraldgrove** [comment]
Good catch. It's possible I didn't actually verify that the program was working when I made my changes.

**Pull request merged**
